swagger: '2.0'
info:
  description: Esto es un ejemplo de la práctica de ASW sobre la API de Hacker News.
  version: 1.0.0
  title: Swagger Hacker News
host: 'localhost:3000'
basePath: /api/v1
schemes: 
  - http
  - https
produces:
  - application/json
securityDefinitions:
  authorization:
    type: apiKey
    description: És la clau d'usuari generada per l'aplicació de Google.
    name: api_key
    in: header
paths:
  /users/update/{id}:
    post:
      security:
        - authorization: []
      tags:
        - users
      description: 
        Updates de info of the user
      consumes: 
        - application/json
      parameters:
        - name: id
          in: path
          description: User identifier
          required: true
          type: number
        - name: userBody
          in: body
          description: Les dades del usuari a modificar
          schema:
            $ref: '#/definitions/UserBody'
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/UserObject'
        default:
          description: Error inesperat
          schema:
            $ref: '#/definitions/Error'
            
  /users/{id}:
    get:
      tags:
        - users
      summary: Gets the user with identifier ID
      parameters:
        - name: id
          in: path
          description: User identifier
          required: true
          type: number
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/UserObject'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
  /users:
    get:
      tags:
        - users
      summary: Gets all users
      description: We get all the submissions in Hacker News
      responses:
        200:
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/UserObject'
        default:
          description: Error inesperat.
          schema:
            $ref: '#/definitions/Error'
definitions:
  UserObject:
    type: object
    properties:
      status:
        type: string
      message:
        type: string
      data:
        $ref: '#/definitions/User'
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
      about:
        type: string
      karma:
        type: integer
      created_at:
        type: string
      updated_at:
        type: string
  UserBody:
    type: object
    properties:
      name:
        type: string
      email:
        type: string
      about:
        type: string
      karma:
        type: integer
      created_at:
        type: string
  Error:
    type: object
    properties:
        code:
          type: integer
          description: codi de l'error.
          format: int32
        message:
          type: string
          description: missatge de l'error.
        fields:
          type: string
          description: camps de l'error.